theme: jekyll-theme-minimal
title: Federico Pecora
description: Senior Manager, Applied Science at Amazon Robotics
logo: https://mrpc.aass.oru.se/wp-content/uploads/people/Federico_Pecora.png
show_downloads: false
